version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: pinger
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: container_monitor
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/internal/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5442:5432"

  backend:
    build:
      context: backend
    environment:
      PORT: 8200
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: container_monitor
      POSTGRES_USER: pinger
      POSTGRES_PASSWORD: strongpassword
    ports:
      - "8200:8200"
    depends_on:
      - postgres

  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  pinger:
    build:
      context: pinger
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - backend

volumes:
  postgres_data: